site_name: Trickster
site_url: https://trickstercache.netlify.app
# site_url: http://tricksterproxy.io/

repo_url: https://github.com/tricksterproxy/trickster
repo_name: tricksterproxy/trickster

theme:
  name: material
  logo: ../../images/logos/trickster-logo.svg
  favicon: ../../images/favicon.ico
  # expand left nav headers. Remove for default of collapsed
  features:
    - navigation.expand
  
  # trickster scheme is defined in extra.css as an override to default theme colors 
  palette:
    - scheme: trickster
      accent: green

# Add extensions to markdown for call outs that are collapsible and can feature code blocks.
# Add permalink feature on headings
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# docs/stylesheets/extra.css overrides default material CSS
extra_css:
  - stylesheets/extra.css


# nav tree
nav:
  - Overview: index.md
  - Getting started:
    - Installing Trickster: installing.md      
    - Try it with Docker Compose: docker-compose.md      
    - Configuring Trickster: configuring.md      
    - Where to Place Trickster: placement.md
  - Origins:
    - Supported Origin Types: supported-origin-types.md
    - Rule Origin: rule.md
    - Using Multiple-Origins with a single Trickster instance: multi-origin.md
    - TLS Support: tls.md
  - Paths:
    - Customizing HTTP Path Behavior: paths.md
    - HTTP Request Rewriters: request-rewriters.md
  - Caching:
    - Cache Options: caches.md
    - Negative Caching: negative-caching.md
    - Trickster Caching Retention Policies: retention.md
    - Byte Range Request Support: range-request.md
  - Tracing and Metrics:
    - Trickster Metrics: metrics.md
    - Distributed Tracing via OpenTelemetry: open-telemetry.md
    - Tracing Support: tracing.md
  - Deployment:
    -  Deployment with Trickster: deployment.md
  - Customizing and Extending Trickster:
      - Adding a New Configuration Value: adding-new-config.md 
      - Extending Trickster to Support a New Origin Type: origin-extensibility.md
      - Spinning a New Trickster Release: spinning-new-release.md
  - Per-Query Time Series Instructions: per-query-instructions.md
  - Release Information:
    - Changelog: new-changed-1.1.md
    - Trickster Roadmap: roadmap.md
    - PromSim Update: promsim.md
    - InfluxDB Support: influxdb.md
  - ClickHouse: clickhouse.md
  - Collapsed Forwarding: collapsed-forwarding.md
  - Health Checks: health.md

  # - Reference:
